### ISSUE TITLE
32 bits version

### ISSUE THREAD

**Issue by OmegaDracula** [WideBoner/betterww#1]
The ww randomizer has a 32 bits version, can you make a 32 bits for this patch too?

**Comment by WideBoner** [comment]
I meant to do it so long ago. Just spent a little bit to figure it out and added a 32 bit version to the releases page, let me know if there are any issues tho.
Thanks and have fun :)

**Comment by OmegaDracula** [comment]
> I meant to do it so long ago. Just spent a little bit to figure it out and added a 32 bit version to the releases page, let me know if there are any issues.
> Thanks and have fun :)

**Comment by OmegaDracula** [comment]
Thank you.
