### ISSUE TITLE
Texture/Model Glitches and possible crashing problems

### ISSUE THREAD

**Issue by AlienJesus** [WideBoner/betterww#2]
This is one of the only glitches I've found and I've had crashing issues but they may be unrelated as I was trying to apply quite a few mods but this is the one is definitely caused by BetterWW as this is an unmodified iso made using it
I've made sure everything is compatible and the right version and such

![image](https://user-images.githubusercontent.com/38385343/86027783-c10a6a00-b9f6-11ea-930e-a0297b642af2.png)

Mods I am trying to use when I had multiple crashes
BetterWW
Hypatia's Textures
Pronoun Swap

**Comment by WideBoner** [comment]
Can you tell me what error message are you getting?
Also does this happen without using the pronoun patch?

**Comment by AlienJesus** [comment]
Yes the image posted is specifically from an unmodified version of the game

As for the errors I'll have to find my log files which I can do in a few minutes I'm currently away from my computer at the moment

**Comment by AlienJesus** [comment]
Okay I forgot to get back to you I couldn't find any crash logs and I haven't had any issues with crashing so I think it was just a coincidence

For the problem with the models I can send you my iso file if that'd help you

**Comment by AlienJesus** [comment]
I just now realized I never tried using a previous version and 1.3a does not have the problem just 1.4

**Comment by WideBoner** [comment]
I can't reproduce it myself
I would rename/delete the Dolphin Emulator folder from documents and use a beta or development version of dolphin, just to make sure this is related to BetterWW
