### ISSUE TITLE
"Reveal full sea chart" for existing saves

### ISSUE THREAD

**Issue by GottemHams** [WideBoner/betterww#3]
Currently the feature only works for brand new saves, but sometimes you might switch to a modded ISO partway through the game. I dunno how exactly it works or how different it is for existing saves, but it would be useful to have this feature for those as well.

By the way, I also tried copying a save but it doesn't count it as brand new so the sea chart isn't updated.

**Comment by WideBoner** [comment]
That is something I would like to do, what is implemented now is just how Lago did it for the randomizer. Until then you could use a code to enable full map, but it says to ONLY use it after meeting the boat. it is in dolphin by default.

Have Fully Detailed Map

Gecko:
023C4D0C 00000303
003C4D3C 00000003

AR:
N3GF-CWJQ-PYV66
Y96X-81AF-68BHV
PK84-91CD-1GRMJ
