### ISSUE TITLE
Keep Normal Sail

### ISSUE THREAD

**Issue by HurricanePootis** [WideBoner/betterww#4]
I love what you have done with BetterWW, but is it possible that you could introduce the option to not mod the sail? I would like to keep the sailing mechanics as it is in the vanilla game. If you are unwilling to do so, could you at least point me in the direction so that I can modify betterww myself to do so?

**Comment by WideBoner** [comment]
I'm sorry for the late reply, I had done this back in October as an update but did not have time to properly test so this is actually already done! I will try to push this update out soon now that I have more time

**Comment by Analogue112** [comment]
> I'm sorry for the late reply, I had done this back in October as an update but did not have time to properly test so this is actually already done! I will try to push this update out soon now that I have more time

Looking forward to this. Thank you for everything.

**Comment by WideBoner** [comment]
Included in the current pre-release, but this is largely untested as of now.
