### ISSUE TITLE
Sail bug 

### ISSUE THREAD

**Issue by Lysc35** [WideBoner/betterww#5]
Hello, 

it seems I have encountered some kind of bug while playing, which locks me on Windfall island. 

The boat does not recognize that I have the fast sail already and does not allow me to keep going. I also don't have to option to buy the normal sail. 

I wonder if this is a recurring bug or maybe just a problem with my game. 

Thank you.

**Comment by WideBoner** [comment]
Sorry if this bug happened to you because of BetterWW and not a cheat code used or something. I have not had anyone else report this and did not run into it in my own testing, but I will make sure to test this with the next update.
