### ISSUE TITLE
Ganon Trials Skipped?

### ISSUE THREAD

**Issue by ArtyDoggo** [WideBoner/betterww#7]
Just did a recent playthrough of Wind Waker using this mod and upon reaching Ganon's Tower the trials were already finished. Is this intentional or is there some option to toggle whether you have to do the trials or not?

**Comment by WideBoner** [comment]
This is unintended, remains from an option in the randomizer and I am finding some code left linked to it. I will try test this and fix it for the next update. Thanks for reporting this!

**Comment by ArtyDoggo** [comment]
Found a save that drops Link right before entering Ganon's tower and upon testing with the new pre-release it would seem the issue is fixed! All trials are left not completed when entering the tower as they should be.

**Comment by chrisasma103** [comment]
> Was this ever fixed

The pre-release version says that this is fixed. I don't know whether that means it is actually fixed or not, but your best bet is to download it and see if it works

**Comment by chrisasma103** [comment]
I played through the entire game and the ganon trials were intact. I think this issue can be closed

**Comment by WideBoner** [comment]
Thank you ArtyDoggo and chrisasma103 for testing! Currently the pre-release fixes this and it will be moved to a main release soon.
