### ISSUE TITLE
Normal for ISO size to get cut in half..?

### ISSUE THREAD

**Issue by n8thegr888** [WideBoner/betterww#8]
I've run the ISO patcher on several USA ISO's (both Nkit and full-size ISOs), so far the game seems to be working but the ISO file size has become really small (~446mb) afterwards compared to the original. Is this normal?

**Comment by edward-Youtube** [comment]
This is completely normal, as the same thing happens with the Randomizer. This size cutting happens to everyone as it optimizes the ISO I believe.
